services:
  - type: web
    name: puertogames-backend
    rootDir: puertogames2/backend/puertogames-api
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.wmvxvbuuxpecjxpwcwsj
      - key: SPRING_DATASOURCE_PASSWORD
        value: PuertoGame123@
