services:
  - type: web
    name: puertogames-backend
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    rootDir: puertogames2/backend/puertogames-api
